name: Release Images

on:
    release:
      types:
        - created

jobs:
    build-php:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                version: ['7.2', '7.3', '7.4', '8.0']
            
        name: 'Docker Image PHP Release ${{ matrix.version }}'

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Information
              run: echo "Building Images for PHP ${{ matrix.version }}"

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .dev/Docker/Images/PHP
                  tags: |
                    tenancy/tenancy-ci-php-${{ matrix.version }}:${{ github.ref }}-latest
                    tenancy/tenancy-ci-php-${{ matrix.version }}:${{ github.ref }}
                    tenancy/tenancy-ci-php-${{ matrix.version }}:latest
                  build-args: |
                    VERSION=${{ matrix.version }}

    build-mysql:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                version: ['5.7', '8']
            
        name: 'Docker Image MySQL Release ${{ matrix.version }}'

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1 
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Information
              run: echo "Building Images for MySQL ${{ matrix.version }}"

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  context: .dev/Docker/Images/MySQL
                  tags: |
                    tenancy/tenancy-ci-mysql-${{ matrix.version }}:${{ github.ref }}-latest
                    tenancy/tenancy-ci-mysql-${{ matrix.version }}:${{ github.ref }}
                    tenancy/tenancy-ci-mysql-${{ matrix.version }}:latest
                  build-args: |
                    VERSION=${{ matrix.version }}
